# fly.toml app configuration file generated for portfolio-backend-spring-boot on 2023-12-08T13:57:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portfolio-backend-spring-boot"
primary_region = "mad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
