# .github/workflows/ci-cd-fly.io.yml

name: Java CI/CD with GitHub Actions, Maven and Fly.io
on:
    pull_request:
    push:
      branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - name: Deploy Spring Boot app to fly.io
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        uses: superfly/flyctl-actions/setup-flyctl@master
              - run: flyctl deploy - remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}